# Project-wide Gradle settings.

# ????? 6 ???????? ?????? (???? 32GB ??? ?????) ?? ????? ???? ??????? ????????
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# ????? ?????? ????????
org.gradle.parallel=true

# ????????? ??????? ?? ??? ????? ??? i7 (8 ?? 10 ?????? ????? ?? 4 ???)
org.gradle.workers.max=10

# ??? ?????? (Task Output Cache)
org.gradle.caching=true

# ????? ??? configuration-cache ?????? ??? ????? ????? ?????? ???????? ?? ??????? 16
org.gradle.configuration-cache=false

# ?????? ???? ??????? ?????? ?????? ????????? ?? ?????
org.gradle.vfs.watch=true

# ????? ????? ???? ??? Daemon ?????? ????????? ?? ?????
kotlin.compiler.execution.strategy=daemon

# Kotlin Code Style
kotlin.code.style=official

# ??????? ???????
android.nonTransitiveRClass=true
googleServices.missing.passthrough=true

# 1. ????? ?????? ???????? ?? Kotlin ???? ????? ????? ??????? ??? ???????
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true

# 2. ????? KSP ??? ????? ???????? (???? Room ? Hilt ? Moshi ???? ????)
ksp.incremental=true
ksp.incremental.intermodule=true
ksp.run.in.process=true

# 3. ????? ????? ?? ??? ??? Dexing
android.enableD8.desugaring=true

# 4. ??? ??? ??????? ???? Lint ??? ??????? ?? ????? ??? Debug
android.buildFeatures.buildConfig=true