# Key Properties for Android App Release Signing
# Copy this file to 'key.properties' and fill in your Android Keystore details.
# DO NOT COMMIT 'key.properties' or your .jks file to source control.

storeFile=my-upload-key.jks
storePassword=quran502008
keyAlias=upload
keyPassword=quran502008
