build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FileBasedIssueReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'HtmlOutputReport'
